### ISSUE TITLE
lowcode-engine依赖安装内容不一样，会导致报错VERSION_PLACEHOLDER is not defined

### ISSUE THREAD

**Issue by fxhfwf** [alibaba/lowcode-engine#408] opened 2022-04-29 04:53 UTC
![image](https://user-images.githubusercontent.com/40874982/165886978-360c2d2e-2a79-4a00-b451-36aa6a774a36.png)

**Comment by LeoYuan** [comment] 2022-04-29 05:56
duplicate of https://github.com/alibaba/lowcode-engine/issues/137#issuecomment-1070148043

**Closed** 2022-04-29 06:44 UTC
