### ISSUE TITLE
demo出码，下载包运行，js报错

### ISSUE THREAD

**Issue by Osub** [alibaba/lowcode-engine#426] opened 2022-05-05 10:28 UTC
React does not recognize the `verAlign` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `veralign` instead. If you accidentally passed it from a parent component, remove it from the DOM element
页面也不是设计的页面
![image](https://user-images.githubusercontent.com/7599190/166905817-18da4108-7ccf-467c-bb61-de6efebb314d.png)

**Comment by liujuping** [comment] 2022-05-05 10:31
辛苦提供完整可复现的步骤/代码。

**Comment by Osub** [comment] 2022-05-06 01:11
1.运行最新版demo
2.点击出码
![image](https://user-images.githubusercontent.com/7599190/167050648-a19c3c39-aa02-48ab-a1f5-d2a29e3123ba.png)

3.下载源码包
4.运行下载的源码
![image](https://user-images.githubusercontent.com/7599190/167050714-586412de-6645-4021-a814-aef8df50e4bc.png)

**Comment by Osub** [comment] 2022-05-06 01:13
项目是好项目，但是一直运行不起来。上手不易呀

**Comment by liujuping** [comment] 2022-05-06 01:50
Duplicate of https://github.com/alibaba/lowcode-engine/issues/429

**Closed** 2022-05-06 08:26 UTC
Labels: duplicate
