### ISSUE TITLE
渲染提示Uncaught ReferenceError: VERSION_PLACEHOLDER is not defined在/node_modules/@alilc/lowcode-engine/es/engine-core.js

### ISSUE THREAD

**Issue by fxhfwf** [alibaba/lowcode-engine#339] opened 2022-04-19 11:43 UTC
渲染提示Uncaught ReferenceError: VERSION_PLACEHOLDER is not defined在/node_modules/@alilc/lowcode-engine/es/engine-core.js

package.json中引入了
@alilc/lowcode-plugin-inject": "^1.0.0",
"@alilc/lowcode-react-renderer": "^1.0.0",

在代码中写入import { injectComponents } from '@alilc/lowcode-plugin-inject';这个就报上面的错

**Comment by liujuping** [comment] 2022-04-19 11:45
Duplicate of https://github.com/alibaba/lowcode-engine/issues/137

**Closed by liujuping** 2022-04-19 11:45 UTC

**Comment by fxhfwf** [comment] 2022-04-19 12:16
npm i lowcode-enigine
