### ISSUE TITLE
创建fetch数据源报错

### ISSUE THREAD

**Issue by duoduoObama** [alibaba/lowcode-engine#164] opened 2022-03-22 10:23 UTC
复现步骤:

1. 创建数据源fetch
2. 填写请求参数value会将name的值给覆盖.
3. 使用代码绑定按钮,再去点击输入框页面渲染出错.
4. 编写好post接口后不能携带post参数到后台.

复现环境:

1. 浏览器系统: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.46
2. 地址: https://alifd.alicdn.com/npm/@alilc/lowcode-demo@1.0.7/build/index.html
![image](https://user-images.githubusercontent.com/30836806/159458065-5868de7e-3943-4824-bd8f-e40ef983c4d0.png)

![image](https://user-images.githubusercontent.com/30836806/159457859-feb95517-ade8-4660-a7a3-57533bc370bd.png)

![image](https://user-images.githubusercontent.com/30836806/159457464-d2910b62-dd8f-481a-9a03-fc8c22de4d83.png)

**Comment by liujuping** [comment] 2022-03-24 11:07
Duplicate of https://github.com/alibaba/lowcode-engine/issues/127

**Closed by liujuping** 2022-03-24 11:07 UTC
Labels: bug
