### ISSUE TITLE
ant-design-pro整合lowcode-engine报错

### ISSUE THREAD

**Issue by chenfeiwu** [alibaba/lowcode-engine#859] opened 2022-07-25 13:28 UTC
---
name: ant-design-pro整合
about: ant-design-pro 6.0.0-beta.1 整合@alilc/lowcode-engine 1.0.12启动后报错，官方文档没有这相关例子等，感觉好难啊
title: ''
labels: ''
assignees: ''

---

## **Describe the bug (required)** / **详细描述 bug（必填）**

![image](https://user-images.githubusercontent.com/14910761/180790851-a992ef18-c527-4d7b-a97f-b035e6f21539.png)
```
TypeError: Cannot set properties of undefined (setting 'PropTypes')
Module../node_modules/_@alilc_lowcode-designer@1.0.12@@alilc/lowcode-designer/es/builtin-simulator/utils/parse-metadata.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:83663:24
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
Module../node_modules/_@alilc_lowcode-designer@1.0.12@@alilc/lowcode-designer/es/builtin-simulator/host.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:81173:80
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
Module../node_modules/_@alilc_lowcode-designer@1.0.12@@alilc/lowcode-designer/es/builtin-simulator/index.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:82882:63
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
Module../node_modules/_@alilc_lowcode-designer@1.0.12@@alilc/lowcode-designer/es/project/project-view.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:96457:76
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
Module../node_modules/_@alilc_lowcode-designer@1.0.12@@alilc/lowcode-designer/es/project/index.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:96437:71
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
Module../node_modules/_@alilc_lowcode-designer@1.0.12@@alilc/lowcode-designer/es/designer/designer.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:85482:67
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
Module../node_modules/_@alilc_lowcode-designer@1.0.12@@alilc/lowcode-designer/es/designer/index.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:87323:67
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
Module../node_modules/_@alilc_lowcode-designer@1.0.12@@alilc/lowcode-designer/es/document/document-model.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:89255:67
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
Module../node_modules/_@alilc_lowcode-designer@1.0.12@@alilc/lowcode-designer/es/document/index.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:90578:73
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
Module../node_modules/_@alilc_lowcode-designer@1.0.12@@alilc/lowcode-designer/es/component-meta.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:84152:67
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
Module../node_modules/_@alilc_lowcode-designer@1.0.12@@alilc/lowcode-designer/es/index.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:95491:73
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
Module../node_modules/_@alilc_lowcode-engine@1.0.12@@alilc/lowcode-engine/es/engine-core.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:115972:81
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
Module../node_modules/.cache/mfsu/mf-va_@alilc_lowcode-engine.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:38:79
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
(anonymous function)
http://localhost:8000/mf-va_remoteEntry.js:1499:105
__webpack_require__.m.<computed>
webpack:/ant-design-pro/webpack/runtime/remotes loading:2481
  2478 | var onFactory = function(factory) {
  2479 | 	data.p = 1;
  2480 | 	__webpack_require__.m[id] = function(module) {
> 2481 | 		module.exports = factory();
       | ^  2482 | 	}
  2483 | };
  2484 | handleFunction(__webpack_require__, data[2], 0, 0, onExternal, 1);
View compiled
options.factory
webpack:/ant-design-pro/webpack/runtime/react refresh:6
  3 | options.factory = function (moduleObject, moduleExports, webpackRequire) {
  4 | 	__webpack_require__.$Refresh$.setup(options.id);
  5 | 	try {
> 6 | 		originalFactory.call(this, moduleObject, moduleExports, webpackRequire);
    | ^  7 | 	} finally {
  8 | 		if (typeof Promise !== 'undefined' && moduleObject.exports instanceof Promise) {
  9 | 			options.module.exports = options.module.exports.then(
View compiled
__webpack_require__
.ant-design-pro/webpack/bootstrap:24
  21 | 	var execOptions = { id: moduleId, module: module, factory: __webpack_modules__[moduleId], require: __webpack_require__ };
  22 | 	__webpack_require__.i.forEach(function(handler) { handler(execOptions); });
  23 | 	module = execOptions.module;
> 24 | 	execOptions.factory.call(module.exports, module, module.exports, execOptions.require);
     | ^  25 | } catch(e) {
  26 | 	module.error = e;
  27 | 	throw e;
View compiled
▶ 3 stack frames were collapsed.
__webpack_require__
.ant-design-pro/webpack/bootstrap:24
  21 | 	var execOptions = { id: moduleId, module: module, factory: __webpack_modules__[moduleId], require: __webpack_require__ };
  22 | 	__webpack_require__.i.forEach(function(handler) { handler(execOptions); });
  23 | 	module = execOptions.module;
> 24 | 	execOptions.factory.call(module.exports, module, module.exports, execOptions.require);
     | ^  25 | } catch(e) {
  26 | 	module.error = e;
  27 | 	throw e;
View compiled
Function.fn
webpack:/ant-design-pro/webpack/runtime/hot module replacement:62
```

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
```
# 使用 npm
npm i @ant-design/pro-cli -g
pro create myapp
umi@4
simple
```
![image](https://user-images.githubusercontent.com/14910761/180791032-414d3154-7339-4fcb-968a-8b66cea73783.png)
![image](https://user-images.githubusercontent.com/14910761/180791081-2c66e39a-759a-4645-a602-244c8f4bf085.png)
![image](https://user-images.githubusercontent.com/14910761/180791298-ba0e91e5-4608-4047-94f2-e35e27a21dca.png)
```javascript
import React, { useState, useEffect } from 'react'
import { project, plugins, common, skeleton } from '@alilc/lowcode-engine'

// 此 schema 参考 demo 中的默认 schema 书写
import userSchema from './schema.json'

export default function EditorView() {
  /** 插件是否已初始化成功，因为必须要等插件初始化后才能渲染 Workbench */
  const [hasPluginInited, setHasPluginInited] = useState(false);

  useEffect(() => {
    plugins.init().then(() => {
      setHasPluginInited(true)
    }).catch(err => console.error(err))
  }, []);

  useEffect(() => {
    project.importSchema(userSchema)
  }, [userSchema]);

  if (!hasPluginInited) {
    return null;
  }

  return (
    <common.skeletonCabin.Workbench
      skeleton={skeleton}
    />
  );
}
```
---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
和Ant Design Pro整合

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [1.0.12] / 低代码引擎版本
 - AliLowCodeEngineExt version: [1.0.4] / 低代码引擎扩展包版本
 - Browser [chrome 97.0.4692.99] / 浏览器版本

**Comment by LeoYuan** [comment] 2022-07-27 09:02
duplicate of #860

**Closed by LeoYuan** 2022-07-27 09:02 UTC
Labels: insufficient information

**Comment by WHSnhcZDYRZC** [comment] 2024-07-13 12:50
可以去看下这个库的解决方案哦
https://github.com/WHSnhcZDYRZC/umi4-lowcode-engine-solutions
