### ISSUE TITLE
渲染工程拉取资源，components有时会返回{}，有时会正常有内容

### ISSUE THREAD

**Issue by fxhfwf** [alibaba/lowcode-engine#381] opened 2022-04-25 09:49 UTC
如何复现：
1. 运行lowcode-demo,点击预览按钮，进入预览页面http://localhost:5556/preview.html
2. 将preview.tsx
    // const packages = JSON.parse(window.localStorage.getItem('packages') || '');
     // const projectSchema = JSON.parse(window.localStorage.getItem('projectSchema') || '');
  这两行代码改为
   let resData
    try{
      const res = await fetch(`https://s3-gzpu-inter.didistatic.com/silver/schema/000/1/online`)
      resData = await res.json()
    }catch(error) {
      console.log("请求资源错误error: ", error)
    }
    const { packages, projectSchema } = resData

3. 打印const components = await injectComponents(buildComponents(libraryMap, componentsMap));这行代码的components,
4. 刷新预览页面，会发现有时候components会是正常的，有时候会返回一个控对象{}(这个是有问题的，会导致页面不能正常预览)

https://s3-gzpu-inter.didistatic.com/silver/schema/000/1/online这个返回的数据可以看下面的

{"packages":[{"package":"moment","version":"2.24.0","urls":["https://g.alicdn.com/mylib/moment/2.24.0/min/moment.min.js"],"library":"moment"},{"package":"lodash","library":"_","urls":["https://g.alicdn.com/platform/c/lodash/4.6.1/lodash.min.js"]},{"package":"iconfont-icons","urls":"//at.alicdn.com/t/font_2369445_ukrtsovd92r.js"},{"package":"@ant-design/icons","version":"4.7.0","urls":["//g.alicdn.com/code/npm/@ali/ant-design-icons-cdn/4.5.0/index.umd.min.js"],"library":"icons"},{"package":"antd","version":"4.19.5","urls":["//g.alicdn.com/code/lib/antd/4.19.4/antd.min.js","//g.alicdn.com/code/lib/antd/4.19.4/antd.min.css"],"library":"antd"},{"title":"fusion组件库","package":"@alifd/next","version":"1.23.0","urls":["https://g.alicdn.com/code/lib/alifd__next/1.23.18/next.min.css","https://g.alicdn.com/code/lib/alifd__next/1.23.18/next-with-locales.min.js"],"library":"Next"},{"package":"@alilc/lowcode-materials","version":"1.0.3","library":"AntdLowcode","urls":["https://alifd.alicdn.com/npm/@alilc/lowcode-materials@1.0.3/build/antd-lowcode/view.js","https://alifd.alicdn.com/npm/@alilc/lowcode-materials@1.0.3/build/antd-lowcode/view.css"],"editUrls":["https://alifd.alicdn.com/npm/@alilc/lowcode-materials@1.0.3/build/antd-lowcode/view.js","https://alifd.alicdn.com/npm/@alilc/lowcode-materials@1.0.3/build/antd-lowcode/view.css"]}],"projectSchema":{"version":"1.0.0","componentsMap":[{"package":"@alilc/lowcode-materials","version":"1.0.3","exportName":"Modal","main":"build/antd-lowcode/view.js","destructuring":true,"componentName":"Modal"},{"package":"@alilc/lowcode-materials","version":"1.0.3","exportName":"Icon","main":"build/antd-lowcode/view.js","destructuring":true,"componentName":"Icon"},{"package":"@alilc/lowcode-materials","version":"1.0.3","exportName":"Button","main":"build/antd-lowcode/view.js","destructuring":true,"componentName":"Button"},{"devMode":"lowcode","componentName":"Page"},{"package":"@alilc/lowcode-materials","version":"1.0.3","exportName":"Menu","main":"build/antd-lowcode/view.js","destructuring":true,"componentName":"Menu"},{"package":"@alilc/lowcode-materials","version":"1.0.3","exportName":"Menu","main":"build/antd-lowcode/view.js","destructuring":true,"subName":"Item","componentName":"Menu.Item"},{"package":"@alilc/lowcode-materials","version":"1.0.3","exportName":"Tag","main":"build/antd-lowcode/view.js","destructuring":true,"componentName":"Tag"},{"package":"@alilc/lowcode-materials","version":"1.0.3","exportName":"Progress","main":"build/antd-lowcode/view.js","destructuring":true,"componentName":"Progress"},{"package":"@alilc/lowcode-materials","version":"1.0.3","exportName":"Typography","main":"build/antd-lowcode/view.js","destructuring":true,"subName":"Link","componentName":"Typography.Link"},{"package":"@alilc/lowcode-materials","version":"1.0.3","exportName":"Breadcrumb","main":"build/antd-lowcode/view.js","destructuring":true,"componentName":"Breadcrumb"},{"package":"@alilc/lowcode-materials","version":"1.0.3","exportName":"Pagination","main":"build/antd-lowcode/view.js","destructuring":true,"componentName":"Pagination"}],"componentsTree":[{"componentName":"Page","id":"node_dockcviv8fo1","props":{"ref":"outerView","style":{"height":"100%"}},"fileName":"/","state":{"text":{"type":"JSExpression","value":"\"outer\""},"isShowDialog":{"type":"JSExpression","value":"false"}},"css":"body {\n  font-size: 12px;\n}\n\n.button {\n  width: 100px;\n  color: #ff00ff\n}","lifeCycles":{"componentDidMount":{"type":"JSFunction","value":"function componentDidMount() {\n  console.log('did mount');\n}"},"componentWillUnmount":{"type":"JSFunction","value":"function componentWillUnmount() {\n  console.log('will unmount');\n}"}},"methods":{"testFunc":{"type":"JSFunction","value":"function testFunc() {\n  console.log('test func');\n}"},"onClick":{"type":"JSFunction","value":"function onClick() {\n  console.log(this);\n  this.dataSourceMap.messageData.load().then(res => {\n    console.log(res);\n    this.setState({\n      messageInfo: res.info\n    });\n  });\n  this.setState({\n    isShowDialog: true\n  });\n}"},"closeDialog":{"type":"JSFunction","value":"function closeDialog() {\n  this.setState({\n    isShowDialog: false\n  });\n}"}},"originCode":"class LowcodeComponent extends Component {\n  state = {\n    \"text\": \"outer\",\n    \"isShowDialog\": false\n  }\n  componentDidMount() {\n    console.log('did mount');\n  }\n  componentWillUnmount() {\n    console.log('will unmount');\n  }\n  testFunc() {\n    console.log('test func');\n  }\n  onClick() {\n    console.log(this)\n    this.dataSourceMap.messageData.load().then(res => {\n      console.log(res)\n      this.setState({\n        messageInfo: res.info\n      })\n    })\n    this.setState({\n      isShowDialog: true\n    })\n  }\n  closeDialog() {\n    this.setState({\n      isShowDialog: false\n    })\n  }\n}","hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":"","dataSource":{"list":[{"type":"fetch","isInit":true,"options":{"params":{},"method":"GET","isCors":true,"timeout":5000,"headers":{},"uri":"/mock/info.json"},"id":"infoData"},{"type":"fetch","isInit":false,"options":{"params":{},"method":"GET","isCors":true,"timeout":5000,"headers":{},"uri":"/mock/data.json"},"id":"messageData"}]},"children":[{"componentName":"Modal","id":"node_ocl2e4xbh93","props":{"title":"Basic Modal","okText":"确认","cancelText":"取消","visible":{"type":"JSExpression","value":"this.state.isShowDialog","mock":true},"destroyOnClose":true,"centered":false,"closable":true,"confirmLoading":false,"forceRender":false,"keyboard":false,"mask":false,"maskClosable":false,"zIndex":0,"bodyStyle":{},"maskStyle":{},"wrapClassName":"","__events":{"eventDataList":[{"type":"componentEvent","name":"onCancel","relatedEventName":"closeDialog"},{"type":"componentEvent","name":"onOk","relatedEventName":"closeDialog"}],"eventList":[{"name":"afterClose","templete":"onCancel(${extParams}){\n// 完全关闭后的回调\nconsole.log('afterClose');}","disabled":false},{"name":"onCancel","template":"onCancel(${extParams}){\n// 点击遮罩层或右上角叉或取消按钮的回调\nconsole.log('onCancel');}","disabled":true},{"name":"onOk","template":"onOk(${extParams}){\n// 点击确定回调\nconsole.log('onOk');}","disabled":true}]},"onCancel":{"type":"JSFunction","value":"function(){this.closeDialog.apply(this,Array.prototype.slice.call(arguments).concat([])) }"},"onOk":{"type":"JSFunction","value":"function(){this.closeDialog.apply(this,Array.prototype.slice.call(arguments).concat([])) }"}},"hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":""},{"componentName":"Button","id":"node_ocl2e4x9f45","props":{"type":"primary","children":{"type":"JSExpression","value":"this.state.infoData?.info","mock":"主按钮"},"htmlType":"button","size":"middle","shape":"default","icon":{"type":"JSSlot","value":[{"componentName":"Icon","id":"node_ocl2e4x9f47","props":{"type":"SearchOutlined","size":14},"hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":""}]},"block":false,"danger":false,"ghost":false,"disabled":false,"__events":{"eventDataList":[{"type":"componentEvent","name":"onClick","relatedEventName":"onClick"}],"eventList":[{"name":"onClick","template":"onClick(event,${extParams}){\n// 点击按钮时的回调\nconsole.log('onClick', event);}","disabled":true}]},"onClick":{"type":"JSFunction","value":"function(){this.onClick.apply(this,Array.prototype.slice.call(arguments).concat([])) }"}},"hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":""},{"componentName":"Button","id":"node_ocl2e4x9f48","props":{"type":"danger","children":{"type":"JSExpression","value":"this.state.messageInfo","mock":"危险按钮"},"htmlType":"button","size":"middle","shape":"default","icon":{"type":"JSSlot","value":[{"componentName":"Icon","id":"node_ocl2e4x9f4a","props":{"type":"SearchOutlined","size":14},"hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":""}]},"block":false,"danger":false,"ghost":false,"disabled":false},"hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":""},{"componentName":"Tag","id":"node_ocl2eblu19j","props":{"color":"magenta","children":"tag","closable":false,"visible":true},"hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":""},{"componentName":"Menu","id":"node_ocl2eblu19d","props":{"mode":"inline","defaultSelectedKeys":["1"],"defaultOpenKeys":["sub1"],"theme":"dark","items":[{"key":"item-i5wd","category":"Menu.Item","children":"菜单名"}],"forceSubMenuRender":false,"inlineCollapsed":false,"inlineIndent":0,"multiple":false,"openKeys":[],"selectable":false,"selectedKeys":[],"subMenuCloseDelay":0,"subMenuOpenDelay":0,"triggerSubMenuAction":"hover"},"hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":"","children":[{"componentName":"Menu.Item","id":"node_ocl2eblu19e","props":{"key":"item-i5wd","children":"菜单名"},"hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":""}]},{"componentName":"Tag","id":"node_ocl2eblu19i","props":{"color":"magenta","children":"tag","closable":false,"visible":true},"hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":""},{"componentName":"Progress","id":"node_ocl2eblu19l","props":{"percent":20,"type":"circle","showInfo":false,"status":"success","strokeLinecap":"round","strokeWidth":0},"hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":""},{"componentName":"Breadcrumb","id":"node_ocl2eblu19n","props":{"routes":[{"path":"a","breadcrumbName":"Home"},{"path":"center","breadcrumbName":"Application Center"},{"path":"app","breadcrumbName":"An Application"}],"itemRender":{"type":"JSSlot","params":["route","params","routes","paths"],"value":[{"componentName":"Typography.Link","id":"node_ocl2eblu19q","props":{"href":{"type":"JSExpression","value":"this.route.path"},"children":{"type":"JSExpression","value":"this.route.breadcrumbName"}},"hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":""}]}},"hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":""},{"componentName":"Progress","id":"node_ocl2eblu19m","props":{"percent":20,"status":"active","type":"line","showInfo":false,"steps":0,"strokeLinecap":"round","strokeWidth":0},"hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":""},{"componentName":"Pagination","id":"node_ocl2eblu19r","props":{"pageSize":10,"total":50,"current":1,"defaultPageSize":10,"defaultCurrent":1,"disabled":false,"showSizeChanger":false,"showQuickJumper":false,"hideOnSinglePage":false,"showLessItems":false,"simple":false,"size":"default","showTitle":false,"responsive":false},"hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":""}]}],"i18n":{}}}

**Comment by fxhfwf** [comment] 2022-04-25 09:50
正常的页面
![image](https://user-images.githubusercontent.com/40874982/165065219-9552b0cc-e1b6-4490-b780-045b616b22f5.png)

不正常的页面
![image](https://user-images.githubusercontent.com/40874982/165065300-3aa33a21-1c8c-4192-9aaa-c43e05f25c78.png)

**Comment by liujuping** [comment] 2022-04-26 04:02
Duplicate of https://github.com/alibaba/lowcode-engine/issues/329

**Comment by liujuping** [comment] 2022-04-26 04:03
这个问题先关掉，将在 https://github.com/alibaba/lowcode-engine/issues/329 中更新进度。

**Closed by liujuping** 2022-04-26 04:03 UTC
