### ISSUE TITLE
用@alilc/element 脚手架开发在低代码模式下，js面板和数据源面板一点就白屏

### ISSUE THREAD

**Issue by wssgchungang** [alibaba/lowcode-engine#184] opened 2022-03-24 07:34 UTC
### 问题描述
用@alilc/element 脚手架开发在低代码模式下，js面板和数据源面板一点就白屏

### 问题截图
![image](https://user-images.githubusercontent.com/29122164/159865264-60f4434f-9f6c-4f04-99d5-df8dec48c4d3.png)
点击后
![image](https://user-images.githubusercontent.com/29122164/159865400-80dec5fd-fecd-4208-a788-c0d05e5667ee.png)

**Comment by alvarto** [comment] 2022-03-24 07:48
duplicate of https://github.com/alibaba/lowcode-engine/issues/100

**Closed** 2022-03-24 11:03 UTC
